[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@host.docker.internal:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"

[chains.arweave-mainnet]
shard = "primary"
protocol = "arweave"
provider = [
  { label = "arweave-mainnet", details = { type = "firehose", url = "https://mainnet.arweave.streamingfast.io:443" , token = ""  }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]
